version: '2'
services:
  vote_postgres:
     image: postgres:alpine
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=vote
     ports:
       - "5432:5432"